### ISSUE TITLE
Error creating project with template

### ISSUE THREAD

**Issue by jhurl3y** [strapi/strapi-template-blog#11]
M1 Macbook Air Big Sur 11.6
```
npx create-strapi-app backend --template https://github.com/strapi/strapi-template-blog
```

```
Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/strapi/strapi-template-blog name version --silent


    at createProject (/Users/jameshurley/.npm/_npx/88206/lib/node_modules/create-strapi-app/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

```
npm view https://github.com/strapi/strapi-template-blog name version
```

```
Invalid package.json
```

**Comment by lukoyanov** [comment]
Same problem here.

**Comment by philj0st** [comment]
same problem.
i tried with node **v17.1.0-3** and **v16.13.1**
both with npm and yarn

**Comment by lukoyanov** [comment]
@markkaylor, @remidej would you please help us out with this issue?

**Comment by markkaylor** [comment]
Hi we have moved templates and starters to npm

Could you try this command
```
yarn create strapi-app my-blog --template blog

## or

npx create-strapi-app my-blog --template blog
```

https://www.npmjs.com/package/@strapi/template-blog
https://github.com/strapi/starters-and-templates

**Comment by markkaylor** [comment]
For v3 Strapi applications you can run:

```
npx create-strapi-app@3.6.8 my-blog --template blog
```

**Comment by jhurl3y** [comment]
Thank you! And appreciate the links.

It might be an idea to update some of the tutorials. I was following along this one: https://strapi.io/blog/build-a-blog-with-next-react-js-strapi

**Comment by jeftarmascarenhas** [comment]
> For v3 Strapi applications you can run:
> 
> ```
> npx create-strapi-app@3.6.8 my-blog --template blog
> ```

@markkaylor thank you!

**Comment by DesignedByNino** [comment]
@jhurl3y I was following the same tutorial and got the exact same issue on a M1 Mac Mini: 
``` 
Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/strapi/strapi-template-blog name version --silent 
at createProject (/Users/nino-popa/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async createQuickStartProject (/Users/nino-popa/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-quickstart-project.js:23:3)


error Command failed.
Exit code: 1
Command: /Users/nino-popa/.yarn/bin/create-strapi-app
Arguments: backend --quickstart --template https://github.com/strapi/strapi-template-blog
Directory: /Users/nino-popa/Code/blog-strapi
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

I have node v14.18.2 as well as the newer LTS release and it does it on both of them.

**Comment by akerd** [comment]
If you use Strapi v4 you can find here the new mono-repo for all official Strapi v4 templates and starters: https://github.com/strapi/starters-and-templates
